language: php

php:
  - 7.1
  - 7.2

sudo: false

cache:
    directories:
        - vendor
        - $HOME/.composer/cache

env:
    global:
        - COMPOSER_PREFER_LOWEST=false
        - SYMFONY_DEPRECATIONS_HELPER=weak
        - SYMFONY_PHPUNIT_BRIDGE_VERSION=3.4.*
        - SYMFONY_VERSION=3.4.*

matrix:
    fast_finish: true
    include:
        - php: 7.1
          env: SYMFONY_VERSION=3.4.* SYMFONY_PHPUNIT_BRIDGE_VERSION=3.4.* SYMFONY_DEPRECATIONS_HELPER=strict
        - php: 7.1
          env: SYMFONY_VERSION=4.0.* SYMFONY_PHPUNIT_BRIDGE_VERSION=4.0.* SYMFONY_DEPRECATIONS_HELPER=strict
        - php: 7.2
          env: SYMFONY_VERSION=4.0.* SYMFONY_PHPUNIT_BRIDGE_VERSION=4.0.* SYMFONY_DEPRECATIONS_HELPER=strict
install:
  - composer require --no-update symfony/symfony:${SYMFONY_VERSION}
  - composer require --no-update symfony/form:${SYMFONY_VERSION}
  - composer require --dev --no-update symfony/phpunit-bridge:${SYMFONY_PHPUNIT_BRIDGE_VERSION}
  - if [[ "$SYMFONY_VERSION" = *dev* ]]; then sed -i "s/\"MIT\"/\"MIT\",\"minimum-stability\":\"dev\"/g" composer.json; fi
  - composer update --prefer-source `if [[ $COMPOSER_PREFER_LOWEST = true ]]; then echo "--prefer-lowest --prefer-stable"; fi`

script: phpunit --coverage-clover=clover.xml

notifications:
  email: helios.ag@gmail.com